---
- hosts: default
  become: yes
  become_user: root
  environment:
    DATABASE_URL: '{{ db_url }}'
  vars:
    app_name: foo
    app_dir: /home/vagrant/src
    python_bin: '{{ app_dir }}/venv/bin/python'
    db_name: '{{ app_name }}'
    db_user: '{{ app_name }}'
    db_password: 'password'
    db_url: 'postgres://{{ db_user }}:{{ db_password }}@localhost/{{ db_name }}'
  tasks:
  - name: Add deadsnakes PPA
    apt_repository: repo='ppa:fkrull/deadsnakes' state=present
  - name: Update APT cache
    apt: update_cache=yes
  - name: Install Python 3.5
    apt: name='{{ item }}' state=present
    with_items:
      - python3.5
      - python3.5-dev
  - name: Install PostgreSQL
    apt: name='{{ item }}' state=installed
    with_items:
      - postgresql
      - postgresql-contrib
      - python-psycopg2
  - name: Ensure PostgreSQL is running
    service: name=postgresql state=started
  - name: Ensure database is created
    become_user: postgres
    postgresql_db:
      name: '{{ db_name }}'
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8
      template: template0
      state: present
  - name: Ensure user has access to the database
    become_user: postgres
    postgresql_user:
      db: '{{ db_name }}'
      name: '{{ db_user }}'
      password: '{{ db_password }}'
      priv: ALL
      state: present
      role_attr_flags: NOSUPERUSER,NOCREATEDB
  - name: Install virtualenv
    apt: name=python-virtualenv state=present
  - name: Install Python dependencies
    pip:
      requirements: '{{ app_dir }}/requirements.txt'
      virtualenv_python: /usr/bin/python3.5
      virtualenv: '{{ app_dir }}/venv'
  - name: Create upstart config for Django
    template: src=templates/django.conf.j2 dest=/etc/init/django.conf
  - name: Run migrations
    django_manage:
      command: migrate
      app_path: '{{ app_dir }}'
      virtualenv: '{{ app_dir }}/venv'
  - name: Start Django
    service: name=django state=restarted
